site_name: RAAFv Pilot Training School
repo_name: VATSIM Learning Centre
repo_url: https://my.vatsim.net/learn
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - nagivation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - conect.tabs.link
    - content.code.annotation
    - content.copde.copy
    - header.autohide
  language: en
  palette:
    - scheme: dafault 
      toggle:
        icon: material/toggle-switch-off-outline
        previous: fontawesome/solid/angle-left
        next: fontawesome/solid/angle-right
        name: Switch to dark mode
      primary: darkblue
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        previous: fontawesome/solid/angle-left
        next: fontawesome/solid/angle-right
      primary: darkblue
      accent: red
  font:
    text: Roboto
  logo: RAAFv_Sticker_Logo_SML.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  plugins:
  - glightbox
  - git-authors

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  - meta # Add front matter to a document
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list # Add HTML attributes and CSS classes to Markdown elements
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
  - pymdownx.details # Additional features to admonition
  - pymdownx.caret # Formatting Extension
  - pymdownx.critic # Alternate Formatting Extension
  - pymdownx.mark # Formatting Extension
  - pymdownx.tilde # Formatting Extension
  - pymdownx.keys # Visual keyboard keys extension
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji: # Allows emoji style inline embeds for icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html #enables the use of image figures
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex: # Allows the use of math formulas with proper formatting
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/raafvirtual
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/raaf_virtual
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/RAAFVirtual
    - icon: fontawesome/solid/paper-plane
      link: mailto:<jeff.arnold@raafvirtual.org>
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


copyright: |
  The content on this webiste is intended for Flight Simulation use only. 